---
repos:
- repo: local
  hooks:
  - id: yamllint
    name: yamllint
    description: This hook runs yamllint.
    entry: yamllint
    language: system
    types: [file, yaml]
  - id: check-topology-version
    name: Check topology version
    description: Check that topology.yml files have version >= 2.0.0
    entry: python3 _tools/check_topology.py
    language: system
    files: topology\.yml$
